server:
  port: ${PORT:8080}

spring:

  main:
    allow-bean-definition-overriding: true

  application:
    name: hotel_api

  datasource:
    driver-class-name: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/hotel_db
    #username: admin
    #password: 123456
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hotel_db}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:123456}
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql
    maxActive: 3
    
  jpa:
    hibernate:
      #ddl-auto: update
      ddl-auto: create-drop
      format_sql: true
    show_sql: true
    #properties:
      #hibernate:
        #dialect: org.hibernate.dialect.PostgreSQL9Dialect
        #dialect: org.hibernate.dialect.PostgreSQLDialect